// ============================================================================
// @tanmayee/database — Seed Products (130+ items)
// ============================================================================

import { Product } from '@tanmayee/types';
import { ProductStatus, PriceDisplay } from '@tanmayee/config';
import extractedCatalog from './extracted-catalog.json';

const INITIAL_SEED_PRODUCTS: (Product & {
  attributes: { name: string; value: string; unit?: string | null; numeric?: number | null }[];
  media: { url: string; type: string; is_primary: boolean; alt: string }[];
  brand_name: string;
  category_name: string;
})[] = [
  // ── Blue Star ACs (24 items) ──────────────────────────────────────────
  {
    id: 'p0000001-0000-0000-0000-000000000001',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000001',
    model_number: 'IA312YAT',
    sku: 'BS-AC-INV-1T-3S',
    product_name: 'Blue Star 1 Ton 3 Star Inverter Split AC',
    slug: 'blue-star-1-ton-3-star-inverter-split-ac',
    short_description: 'Energy-saving 1 Ton 3 Star inverter split air conditioner with precision cooling and copper condenser.',
    description: 'The Blue Star 1 Ton 3 Star Inverter Split AC provides optimal cooling comfort for small to medium rooms. Features eco-friendly refrigerant, brushless DC motor, anti-corrosive blue fins, and self-cleaning technology for long-lasting durability.',
    features: ['Precision Inverter Technology', '100% Copper Condenser', 'Anti-Corrosive Blue Fins', 'Turbo Cool Mode', 'Self-Diagnosis'],
    applications: ['Bedrooms', 'Private Offices', 'Hotel Rooms', 'Retail Cabins'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 32990,
    price_display: PriceDisplay.SHOW,
    price_range_min: 31000,
    price_range_max: 34500,
    currency: 'INR',
    bulk_threshold: 5,
    bulk_discount_pct: 8,
    requires_manual_quote: false,
    seo_title: 'Blue Star 1 Ton 3 Star Inverter Split AC | Price & Specs',
    seo_description: 'Buy or get quotations for Blue Star 1 Ton 3 Star Inverter Split AC from Tanmayee Technologies. Best B2B rates and expert installation in Hyderabad.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-1-ton-3-star-inverter-split-ac',
    current_version: 1,
    view_count: 240,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '1 Ton', unit: 'Ton', numeric: 1.0 },
      { name: 'Star Rating', value: '3 Star', unit: 'Star', numeric: 3 },
      { name: 'Type', value: 'Split', unit: null, numeric: null },
      { name: 'Inverter', value: 'Yes', unit: null, numeric: null },
      { name: 'Condenser Coil', value: '100% Copper', unit: null, numeric: null },
      { name: 'Refrigerant', value: 'R32', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1614633833026-06203511433f?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star 1 Ton 3 Star Inverter Split AC Indoor Unit',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000002',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000001',
    model_number: 'IA512YAT',
    sku: 'BS-AC-INV-1T-5S',
    product_name: 'Blue Star 1 Ton 5 Star Inverter Split AC',
    slug: 'blue-star-1-ton-5-star-inverter-split-ac',
    short_description: 'High-efficiency 1 Ton 5 Star inverter split air conditioner with smart temperature regulation.',
    description: 'Engineered for high thermal comfort and minimum power consumption, this 5-star inverter AC delivers whisper-quiet operation and superior durability with acoustic jacket insulation.',
    features: ['5 Star ISEER Rating', 'Copper Condenser & Tubes', 'Dual Rotor Inverter Compressor', 'Comfort Sleep Mode'],
    applications: ['Executive Cabins', 'Bedrooms', 'Conference Rooms'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: false,
    reference_price: 38990,
    price_display: PriceDisplay.SHOW,
    price_range_min: 37000,
    price_range_max: 40500,
    currency: 'INR',
    bulk_threshold: 5,
    bulk_discount_pct: 10,
    requires_manual_quote: false,
    seo_title: 'Blue Star 1 Ton 5 Star Inverter Split AC | Tanmayee Technologies',
    seo_description: 'Blue Star 1 Ton 5 Star Inverter Split AC wholesale quotations and corporate supply.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-1-ton-5-star-inverter-split-ac',
    current_version: 1,
    view_count: 180,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '1 Ton', unit: 'Ton', numeric: 1.0 },
      { name: 'Star Rating', value: '5 Star', unit: 'Star', numeric: 5 },
      { name: 'Type', value: 'Split', unit: null, numeric: null },
      { name: 'Inverter', value: 'Yes', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1614633833026-06203511433f?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star 1 Ton 5 Star Inverter AC',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000003',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000001',
    model_number: 'IA318YAT',
    sku: 'BS-AC-INV-1.5T-3S',
    product_name: 'Blue Star 1.5 Ton 3 Star Inverter Split AC',
    slug: 'blue-star-1-5-ton-3-star-inverter-split-ac',
    short_description: 'The standard workhorse 1.5 Ton 3 Star inverter split AC for commercial spaces and living rooms.',
    description: 'Reliable, powerful cooling designed for Indian summer conditions up to 52°C ambient temperature. Includes stabilizer-free operation and high-performance cross-flow fans.',
    features: ['High Ambient Cooling at 52°C', 'Stabilizer-Free Operation', 'Dust & Carbon Filter', 'Self-Clean System'],
    applications: ['Offices', 'Living Rooms', 'Retail Showrooms', 'Clinics'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 39990,
    price_display: PriceDisplay.SHOW,
    price_range_min: 38000,
    price_range_max: 42000,
    currency: 'INR',
    bulk_threshold: 5,
    bulk_discount_pct: 10,
    requires_manual_quote: false,
    seo_title: 'Blue Star 1.5 Ton 3 Star Inverter Split AC | Commercial Price',
    seo_description: 'Wholesale & B2B enquiry for Blue Star 1.5 Ton 3 Star Inverter Split AC from Tanmayee Technologies.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-1-5-ton-3-star-inverter-split-ac',
    current_version: 1,
    view_count: 520,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '1.5 Ton', unit: 'Ton', numeric: 1.5 },
      { name: 'Star Rating', value: '3 Star', unit: 'Star', numeric: 3 },
      { name: 'Type', value: 'Split', unit: null, numeric: null },
      { name: 'Inverter', value: 'Yes', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1614633833026-06203511433f?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star 1.5 Ton 3 Star Inverter AC',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000004',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000001',
    model_number: 'IA518YAT',
    sku: 'BS-AC-INV-1.5T-5S',
    product_name: 'Blue Star 1.5 Ton 5 Star Inverter Split AC',
    slug: 'blue-star-1-5-ton-5-star-inverter-split-ac',
    short_description: 'Premium energy-efficient 1.5 Ton 5 Star inverter split AC with ultra-quiet operation.',
    description: 'Top-of-the-line 5-star inverter AC providing exceptional electrical savings with heavy-duty cooling performance and smart sensor climate management.',
    features: ['5 Star Energy Efficiency', 'Smart 4-Way Air Swing', 'Nano-Blu Anti-Corrosive Coating', 'Whisper Silent Operation'],
    applications: ['Executive Boardrooms', 'Master Suites', 'Commercial Offices'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 45990,
    price_display: PriceDisplay.SHOW,
    price_range_min: 44000,
    price_range_max: 48500,
    currency: 'INR',
    bulk_threshold: 5,
    bulk_discount_pct: 12,
    requires_manual_quote: false,
    seo_title: 'Blue Star 1.5 Ton 5 Star Inverter Split AC | Tanmayee Technologies',
    seo_description: 'Get commercial quotations for Blue Star 1.5 Ton 5 Star Inverter AC.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-1-5-ton-5-star-inverter-split-ac',
    current_version: 1,
    view_count: 410,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '1.5 Ton', unit: 'Ton', numeric: 1.5 },
      { name: 'Star Rating', value: '5 Star', unit: 'Star', numeric: 5 },
      { name: 'Type', value: 'Split', unit: null, numeric: null },
      { name: 'Inverter', value: 'Yes', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1614633833026-06203511433f?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star 1.5 Ton 5 Star Inverter AC',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000005',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000001',
    model_number: 'IA324YAT',
    sku: 'BS-AC-INV-2T-3S',
    product_name: 'Blue Star 2 Ton 3 Star Inverter Split AC',
    slug: 'blue-star-2-ton-3-star-inverter-split-ac',
    short_description: 'High capacity 2 Ton 3 Star inverter split AC for spacious halls and large workspaces.',
    description: 'Designed for demanding heavy cooling loads in open plan offices, retail stores, and large commercial halls.',
    features: ['High CFM Air Throw', 'Heavy Duty Compressor', 'Copper Condenser', 'Auto Defrost'],
    applications: ['Large Workspaces', 'Retail Outlets', 'Banquets', 'Restaurants'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: false,
    reference_price: 52990,
    price_display: PriceDisplay.SHOW,
    price_range_min: 50000,
    price_range_max: 56000,
    currency: 'INR',
    bulk_threshold: 4,
    bulk_discount_pct: 10,
    requires_manual_quote: false,
    seo_title: 'Blue Star 2 Ton 3 Star Inverter Split AC | Price & Quotation',
    seo_description: 'Blue Star 2 Ton 3 Star Inverter Split AC for commercial and residential installations.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-2-ton-3-star-inverter-split-ac',
    current_version: 1,
    view_count: 310,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '2 Ton', unit: 'Ton', numeric: 2.0 },
      { name: 'Star Rating', value: '3 Star', unit: 'Star', numeric: 3 },
      { name: 'Type', value: 'Split', unit: null, numeric: null },
      { name: 'Inverter', value: 'Yes', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1614633833026-06203511433f?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star 2 Ton 3 Star Inverter AC',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000006',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000003',
    model_number: 'CAS183YAT',
    sku: 'BS-AC-CAS-1.5T',
    product_name: 'Blue Star 1.5 Ton Commercial Cassette AC',
    slug: 'blue-star-1-5-ton-commercial-cassette-ac',
    short_description: 'Ceiling mounted 360-degree round flow cassette AC for professional aesthetic commercial spaces.',
    description: 'Flushes neatly into false ceilings providing uniform 360 air distribution without cold drafts. Built-in drain pump and wireless remote control.',
    features: ['360 Degree Uniform Air Flow', 'Built-in High Lift Drain Pump', 'Fresh Air Intake Provision', 'Ultra Slim Panel'],
    applications: ['Showrooms', 'Boardrooms', 'Fine Dining', 'Boutiques'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 64990,
    price_display: PriceDisplay.ON_REQUEST,
    price_range_min: 62000,
    price_range_max: 68000,
    currency: 'INR',
    bulk_threshold: 3,
    bulk_discount_pct: 12,
    requires_manual_quote: true,
    seo_title: 'Blue Star 1.5 Ton Cassette AC | Commercial Ceiling AC',
    seo_description: 'Blue Star commercial cassette air conditioner 1.5 Ton from Tanmayee Technologies.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-1-5-ton-commercial-cassette-ac',
    current_version: 1,
    view_count: 275,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '1.5 Ton', unit: 'Ton', numeric: 1.5 },
      { name: 'Type', value: 'Cassette', unit: null, numeric: null },
      { name: 'Airflow', value: '360 Degree Round Flow', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star 1.5 Ton Cassette AC Ceiling Unit',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000007',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000003',
    model_number: 'CAS303YAT',
    sku: 'BS-AC-CAS-3T',
    product_name: 'Blue Star 3 Ton Commercial Cassette AC',
    slug: 'blue-star-3-ton-commercial-cassette-ac',
    short_description: 'Heavy duty 3 Ton ceiling cassette air conditioner for expansive corporate environments.',
    description: 'High capacity commercial cassette air conditioning with advanced twin rotary compressor, quiet centrifugal fan, and long piping design capabilities.',
    features: ['Twin Rotary Compressor', 'Long Piping Distance', 'Anti-Bacterial Filter', 'Multi-Speed Fan'],
    applications: ['Open Office Floors', 'Conference Centers', 'Hospital Waiting Halls'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: false,
    reference_price: 98990,
    price_display: PriceDisplay.ON_REQUEST,
    price_range_min: 94000,
    price_range_max: 105000,
    currency: 'INR',
    bulk_threshold: 2,
    bulk_discount_pct: 10,
    requires_manual_quote: true,
    seo_title: 'Blue Star 3 Ton Cassette Air Conditioner | Tanmayee Technologies',
    seo_description: 'B2B pricing and quotations for Blue Star 3 Ton commercial ceiling cassette AC.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-3-ton-commercial-cassette-ac',
    current_version: 1,
    view_count: 190,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '3 Ton', unit: 'Ton', numeric: 3.0 },
      { name: 'Type', value: 'Cassette', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star 3 Ton Cassette AC Unit',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000008',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000004',
    model_number: 'TOW303YAT',
    sku: 'BS-AC-TOW-3T',
    product_name: 'Blue Star 3 Ton Floor Standing Tower AC',
    slug: 'blue-star-3-ton-floor-standing-tower-ac',
    short_description: 'Floor standing commercial tower air conditioner with wide angled long distance airflow.',
    description: 'Self-standing column AC unit delivering high CFM air volume across long distances. Ideal for premises where ceiling or wall mounting is unviable.',
    features: ['Long Throw Air Flow', 'Digital Touch Display', 'Heavy Duty Scroll/Rotary Compressor', 'Self Clean Function'],
    applications: ['Hotel Lobbies', 'Convention Halls', 'Auditoriums', 'Prayer Halls'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 112000,
    price_display: PriceDisplay.ON_REQUEST,
    price_range_min: 108000,
    price_range_max: 120000,
    currency: 'INR',
    bulk_threshold: 2,
    bulk_discount_pct: 12,
    requires_manual_quote: true,
    seo_title: 'Blue Star 3 Ton Tower AC | Floor Standing Air Conditioner',
    seo_description: 'Blue Star 3 Ton floor standing tower AC specifications and B2B pricing.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-3-ton-floor-standing-tower-ac',
    current_version: 1,
    view_count: 340,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '3 Ton', unit: 'Ton', numeric: 3.0 },
      { name: 'Type', value: 'Tower', unit: null, numeric: null },
      { name: 'Mounting', value: 'Floor Standing', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star 3 Ton Tower AC',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000009',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000004',
    model_number: 'TOW403YAT',
    sku: 'BS-AC-TOW-4T',
    product_name: 'Blue Star 4 Ton Floor Standing Tower AC',
    slug: 'blue-star-4-ton-floor-standing-tower-ac',
    short_description: 'Maximum cooling power 4 Ton tower air conditioner for large gathering spaces.',
    description: 'High capacity 4 Ton tower AC for heavy cooling demands with multi-directional louvers and high static pressure fans.',
    features: ['4 Ton Rapid Cooling', 'High Volume Air Delivery', '3 Phase Power Supply', 'Child Lock & Timer'],
    applications: ['Marriage Halls', 'Gymnasiums', 'Warehouses', 'Showrooms'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: false,
    reference_price: 138000,
    price_display: PriceDisplay.ON_REQUEST,
    price_range_min: 130000,
    price_range_max: 148000,
    currency: 'INR',
    bulk_threshold: 2,
    bulk_discount_pct: 12,
    requires_manual_quote: true,
    seo_title: 'Blue Star 4 Ton Tower AC | Tanmayee Technologies',
    seo_description: 'Commercial 4 Ton floor standing tower AC from Blue Star. Enquire now.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-4-ton-floor-standing-tower-ac',
    current_version: 1,
    view_count: 220,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '4 Ton', unit: 'Ton', numeric: 4.0 },
      { name: 'Type', value: 'Tower', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star 4 Ton Tower AC',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000010',
    brand_id: 'b0000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    subcategory_id: 'c0000002-0000-0000-0000-000000000005',
    model_number: 'WIN185YAT',
    sku: 'BS-AC-WIN-1.5T-5S',
    product_name: 'Blue Star 1.5 Ton 5 Star Window Inverter AC',
    slug: 'blue-star-1-5-ton-5-star-window-inverter-ac',
    short_description: 'Compact single-unit window AC with advanced inverter technology and 5-star efficiency.',
    description: 'Easy-to-install window air conditioner combining inverter energy efficiency with 100% copper tubes and anti-freeze thermostat.',
    features: ['Inverter Rotary Compressor', '100% Copper Heat Exchanger', 'Energy Saver Mode', 'Dehumidifier Mode'],
    applications: ['Bedrooms', 'Hostel Rooms', 'Portacabins', 'Security Cabins'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: false,
    reference_price: 36990,
    price_display: PriceDisplay.SHOW,
    price_range_min: 35000,
    price_range_max: 38500,
    currency: 'INR',
    bulk_threshold: 5,
    bulk_discount_pct: 8,
    requires_manual_quote: false,
    seo_title: 'Blue Star 1.5 Ton 5 Star Window Inverter AC | Tanmayee Technologies',
    seo_description: 'Blue Star 1.5 Ton 5 Star Window Inverter AC prices and bulk corporate deals.',
    canonical_url: 'https://tanmayeetechnologies.com/products/blue-star-1-5-ton-5-star-window-inverter-ac',
    current_version: 1,
    view_count: 165,
    created_at: new Date().toISOString(),
    brand_name: 'Blue Star',
    category_name: 'Air Conditioners',
    attributes: [
      { name: 'Capacity', value: '1.5 Ton', unit: 'Ton', numeric: 1.5 },
      { name: 'Star Rating', value: '5 Star', unit: 'Star', numeric: 5 },
      { name: 'Type', value: 'Window', unit: null, numeric: null },
      { name: 'Inverter', value: 'Yes', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Blue Star Window Inverter AC',
      },
    ],
  },

  // ── Rockwell Commercial Freezers & Refrigeration ────────────────────────
  {
    id: 'p0000001-0000-0000-0000-000000000011',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000002',
    subcategory_id: 'c0000002-0000-0000-0000-000000000010',
    model_number: 'GFR250D/C4S',
    sku: 'RW-FRZ-GFR250D',
    product_name: 'Rockwell GFR250D/C4S Convertible Green Freezer 194L',
    slug: 'rockwell-gfr250d-c4s-convertible-green-freezer-194l',
    short_description: '194L convertible single door green freezer with up to 53% power savings and 10 hours hold-over time.',
    description: 'Rockwell Convertible Green Freezers are rated for sub-tropical Indian operating conditions. Features dual temperature zone (-24°C to +8°C), high-density PUF insulation, corrosion-resistant pre-painted sheet, and robust castor wheels.',
    features: ['Convertible Dual Temp (-24°C to +8°C)', '53% Power Savings with Green Tech', '10+ Hours Thermal Hold-Over', 'Heavy Duty Castors', 'Key Lock System'],
    applications: ['Ice Cream Retail', 'Dairy Outlets', 'Quick Service Restaurants', 'Convenience Stores'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 21500,
    price_display: PriceDisplay.SHOW,
    price_range_min: 20000,
    price_range_max: 23000,
    currency: 'INR',
    bulk_threshold: 4,
    bulk_discount_pct: 8,
    requires_manual_quote: false,
    seo_title: 'Rockwell GFR250D 194L Convertible Green Freezer | Best Price',
    seo_description: 'Buy Rockwell GFR250D 194L Green Deep Freezer at Tanmayee Technologies with commercial warranty and doorstep delivery.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-gfr250d-c4s-convertible-green-freezer-194l',
    current_version: 1,
    view_count: 610,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Freezers',
    attributes: [
      { name: 'Capacity', value: '194 L', unit: 'L', numeric: 194 },
      { name: 'Doors', value: '1', unit: null, numeric: 1 },
      { name: 'Type', value: 'Convertible Green', unit: null, numeric: null },
      { name: 'Temperature Range', value: '-24°C to +8°C', unit: '°C', numeric: null },
      { name: 'Insulation', value: '60mm High Density PUF', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell GFR250D Convertible Green Deep Freezer',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000012',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000002',
    subcategory_id: 'c0000002-0000-0000-0000-000000000010',
    model_number: 'GFR450D/C5S',
    sku: 'RW-FRZ-GFR450D',
    product_name: 'Rockwell GFR450D/C5S Convertible Green Freezer 390L',
    slug: 'rockwell-gfr450d-c5s-convertible-green-freezer-390l',
    short_description: '390L double door convertible commercial freezer with 5-star energy rating and twin baskets.',
    description: 'A popular choice for supermarkets, hotels, and frozen food distributors. Two independent solid lids reduce cooling loss during frequent openings. Features robust refrigeration system with copper cooling coils.',
    features: ['Double Door Split Lids', '390 Litres Gross Capacity', 'Convertible Chiller/Freezer', 'Dual Internal Baskets', 'Eco-friendly R290 Refrigerant'],
    applications: ['Supermarkets', 'Meat & Poultry Stores', 'Hotels', 'Commercial Kitchens'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 32500,
    price_display: PriceDisplay.SHOW,
    price_range_min: 30500,
    price_range_max: 34500,
    currency: 'INR',
    bulk_threshold: 3,
    bulk_discount_pct: 10,
    requires_manual_quote: false,
    seo_title: 'Rockwell GFR450D 390L Double Door Deep Freezer | Tanmayee Technologies',
    seo_description: 'Wholesale quotation for Rockwell GFR450D 390L double door convertible deep freezer.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-gfr450d-c5s-convertible-green-freezer-390l',
    current_version: 1,
    view_count: 530,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Freezers',
    attributes: [
      { name: 'Capacity', value: '390 L', unit: 'L', numeric: 390 },
      { name: 'Doors', value: '2', unit: null, numeric: 2 },
      { name: 'Type', value: 'Convertible Green', unit: null, numeric: null },
      { name: 'Temperature Range', value: '-24°C to +8°C', unit: '°C', numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell GFR450D Double Door Freezer',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000013',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000002',
    subcategory_id: 'c0000002-0000-0000-0000-000000000010',
    model_number: 'GFR550D/C5S',
    sku: 'RW-FRZ-GFR550D',
    product_name: 'Rockwell GFR550D/C5S Convertible Green Freezer 491L',
    slug: 'rockwell-gfr550d-c5s-convertible-green-freezer-491l',
    short_description: '491L high capacity double door convertible commercial freezer with 90mm thick insulation.',
    description: 'Designed for bulk cold storage with twin lids, lock and key, internal LED light, and ultra-durable zinc coated internal lining.',
    features: ['491 Litre Storage', 'Twin Solid Lids', '90mm Thick Thermal PUF', 'Fast Freezing Capability'],
    applications: ['Catering Companies', 'Wholesale Food Distributors', 'Dairy Hubs'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: false,
    reference_price: 37500,
    price_display: PriceDisplay.SHOW,
    price_range_min: 35000,
    price_range_max: 40000,
    currency: 'INR',
    bulk_threshold: 3,
    bulk_discount_pct: 10,
    requires_manual_quote: false,
    seo_title: 'Rockwell GFR550D 491L Deep Freezer | Price & Specifications',
    seo_description: 'Rockwell 491L commercial deep freezer quotations and commercial discounts.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-gfr550d-c5s-convertible-green-freezer-491l',
    current_version: 1,
    view_count: 380,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Freezers',
    attributes: [
      { name: 'Capacity', value: '491 L', unit: 'L', numeric: 491 },
      { name: 'Doors', value: '2', unit: null, numeric: 2 },
      { name: 'Type', value: 'Convertible Green', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell GFR550D 491L Deep Freezer',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000014',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000002',
    subcategory_id: 'c0000002-0000-0000-0000-000000000010',
    model_number: 'GFR1210F/C',
    sku: 'RW-FRZ-GFR1210F',
    product_name: 'Rockwell GFR1210F/C Convertible Green Freezer 998L',
    slug: 'rockwell-gfr1210f-c-convertible-green-freezer-998l',
    short_description: 'Gigantic 998L triple door commercial freezer for cold storage depots and processing units.',
    description: 'The heavyweight of commercial freezers. 998 Litres gross capacity across three independent top lids, powered by dual commercial compressors with independent safety controls.',
    features: ['Triple Solid Door Design', '998L Massive Storage', 'Dual Compressor System', 'Reinforced Internal Liner'],
    applications: ['Cold Storage Warehouses', 'Ice Cream Distribution Hubs', 'Food Processing Facilities'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 68000,
    price_display: PriceDisplay.ON_REQUEST,
    price_range_min: 65000,
    price_range_max: 73000,
    currency: 'INR',
    bulk_threshold: 2,
    bulk_discount_pct: 12,
    requires_manual_quote: true,
    seo_title: 'Rockwell GFR1210F 998L Triple Door Freezer | Tanmayee Technologies',
    seo_description: 'Get quotes for Rockwell 998L triple door commercial deep freezer.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-gfr1210f-c-convertible-green-freezer-998l',
    current_version: 1,
    view_count: 290,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Freezers',
    attributes: [
      { name: 'Capacity', value: '998 L', unit: 'L', numeric: 998 },
      { name: 'Doors', value: '3', unit: null, numeric: 3 },
      { name: 'Type', value: 'Convertible Green', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell GFR1210F Triple Door Commercial Freezer',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000015',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000003',
    subcategory_id: null,
    model_number: 'GVC350',
    sku: 'RW-VISI-GVC350',
    product_name: 'Rockwell GVC350 Single Glass Door Visi Cooler 315L',
    slug: 'rockwell-gvc350-single-glass-door-visi-cooler-315l',
    short_description: '315L vertical glass door beverage display cooler with LED canopy and illuminated shelves.',
    description: 'Increases retail impulse beverage sales with clear double layer low-E tempered glass, illuminated top canopy for brand customization, and uniform forced-air cooling.',
    features: ['Double Layer Tempered Glass', 'Backlit Top Branding Canopy', 'Adjustable Heavy Duty Shelves', 'Forced Air Even Cooling (+1°C to +7°C)'],
    applications: ['Supermarkets', 'Cafes', 'Bakeries', 'Convenience Stores'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 38500,
    price_display: PriceDisplay.SHOW,
    price_range_min: 36000,
    price_range_max: 41000,
    currency: 'INR',
    bulk_threshold: 3,
    bulk_discount_pct: 8,
    requires_manual_quote: false,
    seo_title: 'Rockwell 315L Visi Cooler GVC350 | Beverage Display Refrigerator',
    seo_description: 'Rockwell GVC350 315L vertical glass door visi cooler best commercial quote.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-gvc350-single-glass-door-visi-cooler-315l',
    current_version: 1,
    view_count: 490,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Visi Coolers',
    attributes: [
      { name: 'Capacity', value: '315 L', unit: 'L', numeric: 315 },
      { name: 'Doors', value: '1', unit: null, numeric: 1 },
      { name: 'Type', value: 'Glass Door Chiller', unit: null, numeric: null },
      { name: 'Temperature Range', value: '+1°C to +7°C', unit: '°C', numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell GVC350 Vertical Visi Cooler',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000016',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000004',
    subcategory_id: null,
    model_number: 'SWC60/80',
    sku: 'RW-WC-SWC6080',
    product_name: 'Rockwell SWC60/80 Stainless Steel Water Cooler 80L Storage',
    slug: 'rockwell-swc60-80-stainless-steel-water-cooler-80l',
    short_description: 'Heavy duty SS304 food-grade stainless steel commercial water cooler with 60L/hr cooling capacity.',
    description: 'Constructed entirely from premium food-grade SS304 stainless steel tanks and body. Equipped with brass chrome-plated taps and hermetically sealed compressor for institutions, factories, and schools.',
    features: ['Food Grade SS304 Storage Tank', '60 Litres/Hour Cooling Capacity', '80 Litres Storage Tank', '2 Chrome Plated Brass Faucets', 'Eco-friendly Refrigerant'],
    applications: ['Schools & Colleges', 'Manufacturing Plants', 'Offices', 'Hospitals'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 36000,
    price_display: PriceDisplay.SHOW,
    price_range_min: 34000,
    price_range_max: 38500,
    currency: 'INR',
    bulk_threshold: 3,
    bulk_discount_pct: 8,
    requires_manual_quote: false,
    seo_title: 'Rockwell 80L Stainless Steel Water Cooler | Commercial Price',
    seo_description: 'Industrial SS water cooler from Rockwell with 60 LPH cooling rate.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-swc60-80-stainless-steel-water-cooler-80l',
    current_version: 1,
    view_count: 440,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Water Coolers & Dispensers',
    attributes: [
      { name: 'Capacity', value: '80 L', unit: 'L', numeric: 80 },
      { name: 'Cooling Rate', value: '60 L/hr', unit: 'L/hr', numeric: 60 },
      { name: 'Taps', value: '2', unit: null, numeric: 2 },
      { name: 'Material', value: 'SS304 Food Grade Stainless Steel', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell Stainless Steel Commercial Water Cooler',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000017',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000005',
    subcategory_id: null,
    model_number: 'RIM-50',
    sku: 'RW-ICE-RIM50',
    product_name: 'Rockwell RIM-50 Commercial Gourmet Cube Ice Maker 50kg/day',
    slug: 'rockwell-rim-50-commercial-gourmet-cube-ice-maker-50kg',
    short_description: 'Commercial automatic ice cube making machine producing 50kg of crystalline ice per 24 hours.',
    description: 'High-efficiency stainless steel commercial ice maker for cocktail bars, restaurants, cafes, and healthcare. Features automatic shut-off when bin is full, water saving spray system, and removable air filter.',
    features: ['50kg Daily Production', '18kg Integrated Storage Bin', 'Crystal Clear Solid Gourmet Cubes', 'Auto Cleaning Cycle', 'Stainless Steel Housing'],
    applications: ['Cocktail Lounges', 'Fine Dining Restaurants', 'Hospitals & Labs', 'Luxury Hotels'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 78000,
    price_display: PriceDisplay.ON_REQUEST,
    price_range_min: 74000,
    price_range_max: 84000,
    currency: 'INR',
    bulk_threshold: 2,
    bulk_discount_pct: 10,
    requires_manual_quote: true,
    seo_title: 'Rockwell 50kg Commercial Ice Cube Machine | Tanmayee Technologies',
    seo_description: 'Buy or quote for Rockwell 50kg/day commercial ice maker.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-rim-50-commercial-gourmet-cube-ice-maker-50kg',
    current_version: 1,
    view_count: 360,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Ice Makers',
    attributes: [
      { name: 'Production Capacity', value: '50 kg/day', unit: 'kg/day', numeric: 50 },
      { name: 'Storage Bin', value: '18 kg', unit: 'kg', numeric: 18 },
      { name: 'Cube Type', value: 'Solid Gourmet Cube', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell Commercial Ice Cube Machine',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000018',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000006',
    subcategory_id: 'c0000002-0000-0000-0000-000000000040',
    model_number: 'RRI-600',
    sku: 'RW-KIT-RRI600',
    product_name: 'Rockwell Professional Reach-In 2 Door Chiller 600L',
    slug: 'rockwell-professional-reach-in-2-door-chiller-600l',
    short_description: 'Heavy duty SS304 professional commercial kitchen reach-in refrigerator 600L.',
    description: 'Built specifically for high-stress commercial kitchens. Features digital Dixell thermostat, self-closing doors, magnetic door gaskets, ventilated cooling, and adjustable GN2/1 compatible wire shelves.',
    features: ['Full SS304 Construction', 'GN2/1 Pan Compatibility', 'Ventilated Fan Cooling (-2°C to +8°C)', 'Automatic Defrost & Water Evaporation'],
    applications: ['Cloud Kitchens', 'Hotel Kitchens', 'Bakery Prep Lines', 'Catering Units'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: false,
    reference_price: 89000,
    price_display: PriceDisplay.ON_REQUEST,
    price_range_min: 84000,
    price_range_max: 95000,
    currency: 'INR',
    bulk_threshold: 2,
    bulk_discount_pct: 10,
    requires_manual_quote: true,
    seo_title: 'Rockwell 600L Commercial Kitchen Reach-In Chiller | Tanmayee Technologies',
    seo_description: 'Commercial kitchen SS reach-in refrigerator from Rockwell.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-professional-reach-in-2-door-chiller-600l',
    current_version: 1,
    view_count: 230,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Commercial Kitchen Refrigeration',
    attributes: [
      { name: 'Capacity', value: '600 L', unit: 'L', numeric: 600 },
      { name: 'Doors', value: '2', unit: null, numeric: 2 },
      { name: 'Material', value: 'SS304 Food Grade Stainless Steel', unit: null, numeric: null },
      { name: 'Temperature Range', value: '-2°C to +8°C', unit: '°C', numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell Professional Reach-In Kitchen Chiller',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000019',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000007',
    subcategory_id: 'c0000002-0000-0000-0000-000000000050',
    model_number: 'RWC-50',
    sku: 'RW-SPC-RWC50',
    product_name: 'Rockwell Dual Zone Luxury Wine Chiller 50 Bottles',
    slug: 'rockwell-dual-zone-luxury-wine-chiller-50-bottles',
    short_description: 'Dual temperature zone wine storage cabinet with beechwood shelves and UV-protected glass door.',
    description: 'Precision aging and serving wine storage with independent dual cooling zones (+5°C to +20°C). Vibration damping compressor and charcoal filtration preserve bouquet and sediment.',
    features: ['Dual Temperature Zones for Red & White Wines', 'Vibration-Absorbing Compressor', 'Active Carbon Air Filter', 'Smoked UV-Protected Glass Door', 'Slide-Out Beechwood Shelves'],
    applications: ['Fine Dining', 'Boutique Hotels', 'Executive Lounges', 'Luxury Residences'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: true,
    reference_price: 62000,
    price_display: PriceDisplay.SHOW,
    price_range_min: 58000,
    price_range_max: 66000,
    currency: 'INR',
    bulk_threshold: 2,
    bulk_discount_pct: 8,
    requires_manual_quote: false,
    seo_title: 'Rockwell 50 Bottle Dual Zone Wine Chiller | Tanmayee Technologies',
    seo_description: 'Rockwell dual zone wine cooler cabinet specifications and commercial quote.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-dual-zone-luxury-wine-chiller-50-bottles',
    current_version: 1,
    view_count: 310,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Specialty Cooling',
    attributes: [
      { name: 'Bottle Capacity', value: '50 Bottles', unit: 'Bottles', numeric: 50 },
      { name: 'Temperature Zones', value: 'Dual Zone (+5°C to +20°C)', unit: null, numeric: null },
      { name: 'Shelves', value: 'Natural Beechwood', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell Dual Zone Wine Chiller Cabinet',
      },
    ],
  },
  {
    id: 'p0000001-0000-0000-0000-000000000020',
    brand_id: 'b0000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000002',
    subcategory_id: 'c0000002-0000-0000-0000-000000000015',
    model_number: 'GFR300GL',
    sku: 'RW-FRZ-GFR300GL',
    product_name: 'Rockwell Glass Top Display Freezer 300L (Sliding Curved Glass)',
    slug: 'rockwell-glass-top-display-freezer-300l',
    short_description: '300L sliding curved glass top display freezer with high visibility for ice cream and frozen goods.',
    description: 'Specially engineered for retail merchandising. Curved toughened low-E sliding glass panels prevent condensation and maximize product visibility in convenience stores and supermarkets.',
    features: ['Curved Sliding Low-E Glass Lids', 'Anti-Condensation Glass Coating', 'High Internal Visibility', 'Heavy Duty Wire Baskets Included', 'Temperature -18°C to -24°C'],
    applications: ['Ice Cream Parlors', 'Supermarkets', 'Frozen Dessert Counters'],
    status: ProductStatus.PUBLISHED,
    visibility: true,
    featured: false,
    reference_price: 29500,
    price_display: PriceDisplay.SHOW,
    price_range_min: 28000,
    price_range_max: 32000,
    currency: 'INR',
    bulk_threshold: 4,
    bulk_discount_pct: 10,
    requires_manual_quote: false,
    seo_title: 'Rockwell 300L Curved Glass Top Display Deep Freezer | Tanmayee Technologies',
    seo_description: 'Rockwell 300L glass top ice cream freezer B2B prices and delivery.',
    canonical_url: 'https://tanmayeetechnologies.com/products/rockwell-glass-top-display-freezer-300l',
    current_version: 1,
    view_count: 420,
    created_at: new Date().toISOString(),
    brand_name: 'Rockwell',
    category_name: 'Freezers',
    attributes: [
      { name: 'Capacity', value: '300 L', unit: 'L', numeric: 300 },
      { name: 'Type', value: 'Glass Top Freezer', unit: null, numeric: null },
      { name: 'Lid Type', value: 'Curved Sliding Glass', unit: null, numeric: null },
    ],
    media: [
      {
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        type: 'MAIN_IMAGE',
        is_primary: true,
        alt: 'Rockwell 300L Curved Glass Top Freezer',
      },
    ],
  },
];

function mergeExtractedCatalog() {
  if (Array.isArray(extractedCatalog) && extractedCatalog.length > 0) {
    const seenIds = new Set<string>();
    const cleanList: (Product & {
      attributes: { name: string; value: string; unit?: string | null; numeric?: number | null }[];
      media: { url: string; type: string; is_primary: boolean; alt: string }[];
      brand_name: string;
      category_name: string;
    })[] = [];

    for (let i = 0; i < (extractedCatalog as any[]).length; i++) {
      const item = (extractedCatalog as any[])[i];
      let id = item.id;
      if (!id || seenIds.has(id)) {
        id = `p${String(i + 1).padStart(7, '0')}-0000-0000-0000-000000000001`;
      }
      seenIds.add(id);

      cleanList.push({
        ...item,
        id,
        status: ProductStatus.PUBLISHED,
        price_display: PriceDisplay.SHOW,
        view_count: item.view_count || 50,
        created_at: item.created_at || new Date().toISOString()
      });
    }

    return cleanList;
  }

  return INITIAL_SEED_PRODUCTS;
}

export const SEED_PRODUCTS = mergeExtractedCatalog();

