// ============================================================================
// @tanmayee/database — Seed Data Structures
// Typed repository seed data matching 001_seed_data.sql
// ============================================================================

import { Brand, Category, CategoryAttribute, Service } from '@tanmayee/types';
import { PriceDisplay } from '@tanmayee/config';

export const SEED_BRANDS: Brand[] = [
  {
    id: 'b0000001-0000-0000-0000-000000000001',
    name: 'Blue Star',
    slug: 'blue-star',
    logo_url: '/images/brands/blue-star-logo.png',
    description: "Blue Star Limited is India's leading air conditioning and commercial refrigeration company. Tanmayee Technologies is an authorized and trusted partner for Blue Star products including split ACs, cassette ACs, tower ACs, and window ACs.",
    seo_title: 'Blue Star Commercial & Residential ACs | Tanmayee Technologies',
    seo_description: 'Explore Blue Star air conditioners and cooling solutions available through Tanmayee Technologies. Split ACs, cassette ACs, tower ACs, and window ACs.',
    website_url: 'https://www.bluestarindia.com',
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'b0000001-0000-0000-0000-000000000002',
    name: 'Rockwell',
    slug: 'rockwell',
    logo_url: '/images/brands/rockwell-logo.png',
    description: 'Rockwell Industries Limited is a pioneer and leading manufacturer of commercial refrigeration and cold chain equipment. Tanmayee Technologies offers the full Rockwell range including freezers, visi coolers, water coolers, ice makers, and specialty chillers.',
    seo_title: 'Rockwell Commercial Refrigeration & Freezers | Tanmayee Technologies',
    seo_description: 'Explore Rockwell commercial refrigeration products available through Tanmayee Technologies. Freezers, visi coolers, water coolers, ice makers, and more.',
    website_url: 'https://www.rockwellindia.com',
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const SEED_CATEGORIES: Category[] = [
  // Parent Categories
  {
    id: 'c0000001-0000-0000-0000-000000000001',
    parent_id: null,
    name: 'Air Conditioners',
    slug: 'air-conditioners',
    description: 'Commercial and residential air conditioning solutions from Blue Star. Inverter split ACs, cassette ACs, tower ACs, and window ACs for every commercial application.',
    image_url: '/images/categories/air-conditioners.jpg',
    seo_title: 'Air Conditioners & Cooling Systems | Tanmayee Technologies',
    seo_description: 'Browse commercial air conditioners from Blue Star at Tanmayee Technologies. Inverter split ACs, cassette ACs, tower ACs, and window ACs.',
    sort_order: 1,
    is_active: true,
    product_count: 24,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000001-0000-0000-0000-000000000002',
    parent_id: null,
    name: 'Freezers',
    slug: 'freezers',
    description: 'Commercial freezers and cold storage solutions from Rockwell. Green freezers, hard top freezers, glass top freezers, eutectic freezers, and blast freezers.',
    image_url: '/images/categories/freezers.jpg',
    seo_title: 'Commercial Freezers & Deep Freezers | Tanmayee Technologies',
    seo_description: 'Browse Rockwell commercial freezers at Tanmayee Technologies. Green freezers, hard top freezers, glass top freezers, and blast freezers.',
    sort_order: 2,
    is_active: true,
    product_count: 36,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000001-0000-0000-0000-000000000003',
    parent_id: null,
    name: 'Visi Coolers',
    slug: 'visi-coolers',
    description: 'Commercial display coolers and visi freezers from Rockwell for retail, supermarkets, hospitality, and beverage merchandising.',
    image_url: '/images/categories/visi-coolers.jpg',
    seo_title: 'Commercial Visi Coolers & Display Fridges | Tanmayee Technologies',
    seo_description: 'Browse Rockwell visi coolers and glass door display coolers at Tanmayee Technologies.',
    sort_order: 3,
    is_active: true,
    product_count: 14,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000001-0000-0000-0000-000000000004',
    parent_id: null,
    name: 'Water Coolers & Dispensers',
    slug: 'water-coolers-dispensers',
    description: 'Heavy duty stainless steel water coolers and bottled water dispensers from Rockwell for commercial facilities, offices, and institutions.',
    image_url: '/images/categories/water-coolers.jpg',
    seo_title: 'Commercial Water Coolers & Dispensers | Tanmayee Technologies',
    seo_description: 'Browse Rockwell water coolers and dispensers at Tanmayee Technologies.',
    sort_order: 4,
    is_active: true,
    product_count: 12,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000001-0000-0000-0000-000000000005',
    parent_id: null,
    name: 'Ice Makers',
    slug: 'ice-makers',
    description: 'Commercial cube and bullet ice makers from Rockwell for hospitality, bars, food service, and laboratory use.',
    image_url: '/images/categories/ice-makers.jpg',
    seo_title: 'Commercial Ice Machines & Makers | Tanmayee Technologies',
    seo_description: 'Browse Rockwell commercial ice makers at Tanmayee Technologies.',
    sort_order: 5,
    is_active: true,
    product_count: 8,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000001-0000-0000-0000-000000000006',
    parent_id: null,
    name: 'Commercial Kitchen Refrigeration',
    slug: 'commercial-kitchen-refrigeration',
    description: 'Professional reach-in chillers, freezers, under-counter work tables, and back bar coolers from Rockwell.',
    image_url: '/images/categories/kitchen-refrigeration.jpg',
    seo_title: 'Commercial Kitchen Refrigeration | Tanmayee Technologies',
    seo_description: 'Browse Rockwell commercial kitchen refrigeration at Tanmayee Technologies.',
    sort_order: 6,
    is_active: true,
    product_count: 16,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000001-0000-0000-0000-000000000007',
    parent_id: null,
    name: 'Specialty Cooling',
    slug: 'specialty-cooling',
    description: 'Specialty wine chillers, portable car coolers, mini refrigerators, and confectionery showcases from Rockwell.',
    image_url: '/images/categories/specialty-cooling.jpg',
    seo_title: 'Specialty Cooling Solutions | Tanmayee Technologies',
    seo_description: 'Browse Rockwell specialty cooling products at Tanmayee Technologies.',
    sort_order: 7,
    is_active: true,
    product_count: 10,
    created_at: new Date().toISOString(),
  },

  // Subcategories - ACs
  {
    id: 'c0000002-0000-0000-0000-000000000001',
    parent_id: 'c0000001-0000-0000-0000-000000000001',
    name: 'Inverter Split AC',
    slug: 'inverter-split-ac',
    description: 'Energy-efficient inverter split air conditioners from Blue Star.',
    image_url: null,
    seo_title: 'Inverter Split ACs | Blue Star | Tanmayee Technologies',
    seo_description: 'Blue Star inverter split air conditioners.',
    sort_order: 1,
    is_active: true,
    product_count: 6,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000002-0000-0000-0000-000000000002',
    parent_id: 'c0000001-0000-0000-0000-000000000001',
    name: 'Non-Inverter Split AC',
    slug: 'non-inverter-split-ac',
    description: 'Reliable non-inverter split air conditioners from Blue Star.',
    image_url: null,
    seo_title: 'Non-Inverter Split ACs | Blue Star | Tanmayee Technologies',
    seo_description: 'Blue Star non-inverter split air conditioners.',
    sort_order: 2,
    is_active: true,
    product_count: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000002-0000-0000-0000-000000000003',
    parent_id: 'c0000001-0000-0000-0000-000000000001',
    name: 'Cassette AC',
    slug: 'cassette-ac',
    description: 'Commercial ceiling cassette air conditioners from Blue Star for offices and showrooms.',
    image_url: null,
    seo_title: 'Cassette ACs | Blue Star | Tanmayee Technologies',
    seo_description: 'Blue Star commercial cassette ACs.',
    sort_order: 3,
    is_active: true,
    product_count: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000002-0000-0000-0000-000000000004',
    parent_id: 'c0000001-0000-0000-0000-000000000001',
    name: 'Tower AC',
    slug: 'tower-ac',
    description: 'High-capacity tower floor standing air conditioners from Blue Star for large halls.',
    image_url: null,
    seo_title: 'Tower ACs | Blue Star | Tanmayee Technologies',
    seo_description: 'Blue Star commercial tower air conditioners.',
    sort_order: 4,
    is_active: true,
    product_count: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000002-0000-0000-0000-000000000005',
    parent_id: 'c0000001-0000-0000-0000-000000000001',
    name: 'Window Inverter AC',
    slug: 'window-inverter-ac',
    description: 'Energy-saving window inverter air conditioners from Blue Star.',
    image_url: null,
    seo_title: 'Window Inverter ACs | Blue Star | Tanmayee Technologies',
    seo_description: 'Blue Star window inverter air conditioners.',
    sort_order: 5,
    is_active: true,
    product_count: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c0000002-0000-0000-0000-000000000006',
    parent_id: 'c0000001-0000-0000-0000-000000000001',
    name: 'Window Non-Inverter AC',
    slug: 'window-non-inverter-ac',
    description: 'Heavy duty window non-inverter air conditioners from Blue Star.',
    image_url: null,
    seo_title: 'Window Non-Inverter ACs | Blue Star | Tanmayee Technologies',
    seo_description: 'Blue Star window non-inverter air conditioners.',
    sort_order: 6,
    is_active: true,
    product_count: 2,
    created_at: new Date().toISOString(),
  },
];

export const SEED_SERVICES: Service[] = [
  {
    id: 's0000001-0000-0000-0000-000000000001',
    name: 'AC Installation',
    slug: 'ac-installation',
    short_description: 'Certified commercial & residential air conditioner installation.',
    description: 'Expert installation of split, cassette, tower, and window air conditioning units. Trained technicians ensure vibration-free mounting, vacuuming, and optimal refrigerant charge for peak efficiency.',
    image_url: '/images/services/ac-installation.jpg',
    base_price: null,
    price_display: PriceDisplay.ON_REQUEST,
    is_active: true,
    seo_title: 'Professional AC Installation Services | Tanmayee Technologies',
    seo_description: 'Commercial AC installation for Blue Star systems by certified engineers at Tanmayee Technologies.',
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 's0000001-0000-0000-0000-000000000002',
    name: 'AC Maintenance & Preventive Service',
    slug: 'ac-maintenance-service',
    short_description: 'Regular preventative servicing, coil cleaning, and leak checks.',
    description: 'Comprehensive preventative AC maintenance including high-pressure coil wash, gas pressure checks, electrical terminal inspection, and filter replacement for trouble-free cooling.',
    image_url: '/images/services/ac-maintenance.jpg',
    base_price: null,
    price_display: PriceDisplay.ON_REQUEST,
    is_active: true,
    seo_title: 'Commercial AC Maintenance & Servicing | Tanmayee Technologies',
    seo_description: 'Preventive AC service and repairs in Hyderabad & Telangana.',
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 's0000001-0000-0000-0000-000000000003',
    name: 'Commercial Freezer Installation & Commissioning',
    slug: 'freezer-installation',
    short_description: 'Commercial deep freezer and blast freezer installation.',
    description: 'Complete commissioning of commercial refrigeration units, cold rooms, and eutectic systems with proper electrical and drainage connections.',
    image_url: '/images/services/freezer-installation.jpg',
    base_price: null,
    price_display: PriceDisplay.ON_REQUEST,
    is_active: true,
    seo_title: 'Commercial Freezer Installation | Tanmayee Technologies',
    seo_description: 'Rockwell commercial freezer and cold room setup services.',
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 's0000001-0000-0000-0000-000000000004',
    name: 'Annual Maintenance Contract (AMC)',
    slug: 'annual-maintenance-contract',
    short_description: 'Comprehensive AMC with priority emergency support.',
    description: 'Year-round cooling peace of mind with scheduled periodic check-ups, unlimited breakdown calls, priority technician dispatch, and discounted spares support.',
    image_url: '/images/services/amc.jpg',
    base_price: null,
    price_display: PriceDisplay.ON_REQUEST,
    is_active: true,
    seo_title: 'Annual Maintenance Contract (AMC) | Tanmayee Technologies',
    seo_description: 'Comprehensive cooling AMC plans for businesses, restaurants, hotels, and hospitals.',
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
];

export const SEED_CATEGORY_ATTRIBUTES: CategoryAttribute[] = [
  {
    id: 'ca000001-0000-0000-0000-000000000001',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    attribute_name: 'Capacity',
    attribute_type: 'enum',
    attribute_unit: 'Ton',
    filter_type: 'select',
    possible_values: ['1 Ton', '1.5 Ton', '2 Ton', '2.5 Ton', '3 Ton', '4 Ton'],
    is_filterable: true,
    is_comparable: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ca000001-0000-0000-0000-000000000002',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    attribute_name: 'Star Rating',
    attribute_type: 'enum',
    attribute_unit: 'Star',
    filter_type: 'select',
    possible_values: ['2 Star', '3 Star', '5 Star'],
    is_filterable: true,
    is_comparable: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ca000001-0000-0000-0000-000000000003',
    category_id: 'c0000001-0000-0000-0000-000000000001',
    attribute_name: 'Type',
    attribute_type: 'enum',
    attribute_unit: null,
    filter_type: 'select',
    possible_values: ['Split', 'Cassette', 'Tower', 'Window'],
    is_filterable: true,
    is_comparable: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ca000001-0000-0000-0000-000000000004',
    category_id: 'c0000001-0000-0000-0000-000000000002',
    attribute_name: 'Capacity',
    attribute_type: 'number',
    attribute_unit: 'L',
    filter_type: 'range',
    possible_values: null,
    is_filterable: true,
    is_comparable: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ca000001-0000-0000-0000-000000000005',
    category_id: 'c0000001-0000-0000-0000-000000000002',
    attribute_name: 'Doors',
    attribute_type: 'enum',
    attribute_unit: null,
    filter_type: 'select',
    possible_values: ['1', '2', '3'],
    is_filterable: true,
    is_comparable: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
];
